package org.narrativ27.vysshijvyvod;

public class EncyclopediaContent
{
    public static final String[] TITLES = {
        "ABOUT",
        "FONTS",
        "ROMAN",
        "GOTHIC",
        "CALLIGRAPHIC",
        "RUNIC"
    };

    public static final String[] TEXTS = {
        "This Encyclopedia is your personal guide to the lore and typography of the universe. Here you can explore the history of written communication as it evolved from ancient carvings to interstellar interfaces. Use the mouse wheel to scroll through the tree, click on any node to read an article, and click the BACK button at the bottom to return. The tree shows the relationship between different writing systems: from general knowledge about fonts to the specific scripts used by various factions. Every article blends real‑world historical facts with in‑game fiction, helping you understand the cultural and strategic significance of each typeface. We hope this knowledge will aid you in your journey through the stars.",
        "A font is a set of glyphs—letters, numbers, and symbols—that share a common design. Long before digital screens, humans carved letters into stone, wood, and metal. The shape of these characters was often dictated by the tools used to create them. In our universe, fonts are more than just decoration: they carry the identity of entire civilizations. The Interface uses Roman serifs to project authority and order, while the outlaw Devils prefer jagged Gothic letters that mirror their chaotic nature. Angels, the benevolent colonizers, write in flowing calligraphy that suggests culture and compassion. The Wild tribes, untamed and free, rely on runes—angular symbols originally designed for carving. This encyclopedia explores each of these scripts, explaining both their real history and their role in the galactic struggle.",
        "Roman letterforms trace their origins to the majestic capitalis monumentalis inscribed on Trajan's Column in Rome around 113 AD. These serifed characters, with their elegant proportions and subtle variations in stroke weight, have become the enduring voice of imperial authority. In our universe, the Roman font is the official typeface of the Interface—the administrative backbone of the Dominion. It is used for all official decrees, navigation consoles, and command‑line interfaces. Real‑world type designers like Carol Twombly have revived this classical spirit in digital fonts such as Trajan, proving that letters carved in stone millennia ago still convey order and power. The Roman style represents clarity, tradition, and unyielding control. Every strategic decision you make is displayed in this timeless script, reminding you that civilization stands on the shoulders of ancient giants.",
        "Gothic script, also known as blackletter or Textura, originated in medieval Europe around the 12th century. Its dense, angular strokes and dramatic contrast between thick and thin lines gave it an aura of mystery and solemnity. It was used for magnificent illuminated manuscripts, Bibles, and eventually became associated with the printing press of Gutenberg. In our cosmos, Gothic is the voice of the Devils—outlaw pirates, rogue scavengers, and heretics who inhabit the lawless sectors of space. Their ships are adorned with jagged inscriptions that echo the anarchy of their crews. Historically, blackletter fell out of favor for readability reasons, but its evocative power endures. It speaks of rebellion, dark rituals, and the chaotic beauty of destruction. When you encounter a Devil communiqué, its Gothic letters warn you of danger before you read a single word.",
        "Calligraphic scripts have roots in the humanist minuscule of the Renaissance, which sought to revive the fluidity of ancient Roman cursive. Unlike the rigid formality of Roman capitals, calligraphy flows with organic curves, ligatures, and a sense of personal touch. It became the script of diplomats, scholars, and poets. In our galaxy, the Angels—benevolent colonizers and keepers of knowledge—use a calligraphic font as their hallmark. Their vessels broadcast messages of peace in graceful, handwritten‑like letters. Real‑world calligraphers emphasize rhythm and expression, values that the Angels cherish as they explore and uplift nascent civilizations. This font is not just a means of communication; it is a symbol of compassion and enlightenment. Every treaty, every declaration of protection is penned in this elegant hand, reminding us that strength can be gentle.",
        "Runes are the letters of the ancient Germanic alphabets, used from around the 2nd century AD across Northern Europe. Carved on wood, stone, and metal, each rune was imbued with magical and divinatory meaning. The angular shapes—straight lines and no curves—were designed for ease of carving rather than writing. In our world, the Wild ones—fierce indigenous tribes living on the fringes of explored space—employ a runic script for their rituals and communication. Their shamans believe that each rune is a fragment of the universe's primal code. The real‑world Elder Futhark runes inspired this living tradition, where literacy is a form of power. To encounter runic text is to feel the raw, untamed energy of a culture that refuses to be assimilated. It is the script of freedom, nature, and the arcane."
    };
}
